### ISSUE TITLE
不好意思，大佬，那个firehose的链接似乎是挂了啊（腾讯微云的）

### ISSUE THREAD

**Issue by Xingeqwd** [kaneorotar/LG-V35-Tinkering-Instructions#1]
所幸是在XDA上面找到了一个，但是似乎不太管用（按道理来说，这个programmer应该对所有845的V系列LG手机通用才对罢）
9008那边报错，get GPT download fail sahara fail 之类的
手机也进过好几次那个页面了，线也换过了很多跟，连电脑都换过了
咳咳咳，仍然是这个错误，的确是非常的离谱罢
有一篇另一位大佬XDA写的文章要求是用8，但是我用的是9（GITHUB这边这里写的是9罢），不知道会不会是版本问题呐（因为记得那边错误代码里面好像有个P，Pie代表9吧）
顺带一提，敝人的设备是V35。。。根据硬件号码和IMAI比对，应该是美国那块的机器（是350AM什么的型号）——应该是没关系吧，我想，这个应该是全系列通用的，毕竟不是ROM补丁包，印象中也没有看到谁有提过这个不能混用（安卓版本问题倒是看起来挺严重的）

实在是有些，顶不住了，不然我会试试其他方法的，干不下去了，所以强撑着来打了这么两段话（兴许明天会有奇迹呢。。。）

咳咳咳，接连几天没睡觉，精神状态不太好，很多东西一下子都想不起来，内容比较缺失了吧...

**Comment by kaneorotar** [comment]
测试了一下firehose的链接还是可以用的。注意请不要直接右键另存为，需要点击链接后才能看到真正的链接。

具体是在哪个步骤遇到的错误？

由于个人的手机早已更换，所以只能凭借模糊的印象提供建议。

**Comment by Xingeqwd** [comment]
> 测试了一下firehose的链接还是可以用的。注意请不要直接右键另存为，需要点击链接后才能看到真正的链接。
> 
> 具体是在哪个步骤遇到的错误？
> 
> 由于个人的手机早已更换，所以只能凭借模糊的印象提供建议。

没事了，大佬，那天之后的第二天，我也是把他成功刷完了，感谢大佬，大佬辛苦了
当时应该也是玩的9008，按键进入刷的，也用了几个工具，所幸是刷成功了哈，感谢大佬！

——真没想到啊，这么久之后还能看得到大佬回复，大佬威武！
